#ifndef OPACIMETRO_GLOBAL_H
#define OPACIMETRO_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef OPACIMETRO_LIBRARY
#  define OPACIMETROSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPACIMETROSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPACIMETRO_GLOBAL_H
