//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace machineConfiguration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("machineConfiguration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;MachineConfiguration&gt;
        ///  &lt;StartupDelaySec&gt;210&lt;/StartupDelaySec&gt;
        ///  &lt;ViewSplashScreen&gt;-1&lt;/ViewSplashScreen&gt;
        ///  &lt;NodeBootTimeoutSec&gt;30&lt;/NodeBootTimeoutSec&gt;
        ///  &lt;BypassHMIsendRecipe&gt;false&lt;/BypassHMIsendRecipe&gt;
        ///  &lt;EnableAudit&gt;true&lt;/EnableAudit&gt;
        ///  &lt;BypassHMIsendResults&gt;true&lt;/BypassHMIsendResults&gt;
        ///  &lt;Customer&gt;SPAMI&lt;/Customer&gt;
        ///  &lt;DefaultFolder&gt;D:\SPAMI&lt;/DefaultFolder&gt;
        ///  &lt;DebugEnabled&gt;true&lt;/DebugEnabled&gt;
        ///  &lt;UseConsole&gt;false&lt;/UseConsole&gt;
        ///  &lt;ConsoleLevel&gt;0&lt;/ConsoleLevel&gt;
        ///  &lt;WriteLogToFile&gt;true&lt;/WriteLogToFile [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string machineConfigExample {
            get {
                return ResourceManager.GetString("machineConfigExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SG_OneEngineering {
            get {
                object obj = ResourceManager.GetObject("SG_OneEngineering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
