//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExactaEasy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExactaEasy.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get acquisition parameters from camera {0}.
        /// </summary>
        internal static string AcquisitionGetError {
            get {
                return ResourceManager.GetString("AcquisitionGetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition parameter.
        /// </summary>
        internal static string AcquisitionParameter {
            get {
                return ResourceManager.GetString("AcquisitionParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual value.
        /// </summary>
        internal static string ActualValue {
            get {
                return ResourceManager.GetString("ActualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced recipe parameter.
        /// </summary>
        internal static string AdvancedRecipeParameter {
            get {
                return ResourceManager.GetString("AdvancedRecipeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistants.
        /// </summary>
        internal static string Assistants {
            get {
                return ResourceManager.GetString("Assistants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one enable camera in error.
        /// </summary>
        internal static string AtLeastOneCameraInError {
            get {
                return ResourceManager.GetString("AtLeastOneCameraInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit failed.
        /// </summary>
        internal static string AuditFailed {
            get {
                return ResourceManager.GetString("AuditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup camera parameters failed.
        /// </summary>
        internal static string BackupCamParamsFailed {
            get {
                return ResourceManager.GetString("BackupCamParamsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup / Restore.
        /// </summary>
        internal static string BackupRestore {
            get {
                return ResourceManager.GetString("BackupRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup camera vial axis failed.
        /// </summary>
        internal static string BackupVialAxisFailed {
            get {
                return ResourceManager.GetString("BackupVialAxisFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        internal static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string BtnApply {
            get {
                return ResourceManager.GetString("BtnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string BtnConfig {
            get {
                return ResourceManager.GetString("BtnConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROI start live.
        /// </summary>
        internal static string BtnLiveStart {
            get {
                return ResourceManager.GetString("BtnLiveStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullframe start live.
        /// </summary>
        internal static string BtnLiveStartFF {
            get {
                return ResourceManager.GetString("BtnLiveStartFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROI stop live.
        /// </summary>
        internal static string BtnLiveStop {
            get {
                return ResourceManager.GetString("BtnLiveStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullframe stop live.
        /// </summary>
        internal static string BtnLiveStopFF {
            get {
                return ResourceManager.GetString("BtnLiveStopFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string BtnUndo {
            get {
                return ResourceManager.GetString("BtnUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not apply HMI recipe.
        /// </summary>
        internal static string BypassHMIsendRecipe {
            get {
                return ResourceManager.GetString("BypassHMIsendRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera error.
        /// </summary>
        internal static string CameraError {
            get {
                return ResourceManager.GetString("CameraError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera list.
        /// </summary>
        internal static string CameraList {
            get {
                return ResourceManager.GetString("CameraList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera no: {0} ip: {1} not found on configuration setting.
        /// </summary>
        internal static string CameraNotFound {
            get {
                return ResourceManager.GetString("CameraNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera not found.
        /// </summary>
        internal static string CameraNotFound2 {
            get {
                return ResourceManager.GetString("CameraNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera not ready.
        /// </summary>
        internal static string CameraNotReady {
            get {
                return ResourceManager.GetString("CameraNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera parameters backup successful.
        /// </summary>
        internal static string CameraParamsBackupOk {
            get {
                return ResourceManager.GetString("CameraParamsBackupOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera recipe not found.
        /// </summary>
        internal static string CameraRecipeNotFound {
            get {
                return ResourceManager.GetString("CameraRecipeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera is restarting... Please wait.
        /// </summary>
        internal static string CameraResetting {
            get {
                return ResourceManager.GetString("CameraResetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras.
        /// </summary>
        internal static string Cameras {
            get {
                return ResourceManager.GetString("Cameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera status.
        /// </summary>
        internal static string CameraStatus {
            get {
                return ResourceManager.GetString("CameraStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera status not available.
        /// </summary>
        internal static string CameraStatusNotAvailable {
            get {
                return ResourceManager.GetString("CameraStatusNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot bind to camera.
        /// </summary>
        internal static string CantBindToCamera {
            get {
                return ResourceManager.GetString("CantBindToCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change language while machine is running.
        /// </summary>
        internal static string CantChangeLanguageWhileMachineIsRunning {
            get {
                return ResourceManager.GetString("CantChangeLanguageWhileMachineIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find global configuration file &quot;globalConfig.xml&quot;.
        /// </summary>
        internal static string CantFindGlobalConfig {
            get {
                return ResourceManager.GetString("CantFindGlobalConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save recipe.
        /// </summary>
        internal static string CantSaveRecipe {
            get {
                return ResourceManager.GetString("CantSaveRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save recipe while machine is running.
        /// </summary>
        internal static string CantSaveRecipeWhileMachineRunning {
            get {
                return ResourceManager.GetString("CantSaveRecipeWhileMachineRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check vial axis.
        /// </summary>
        internal static string CheckVialAxis {
            get {
                return ResourceManager.GetString("CheckVialAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer evaluation.
        /// </summary>
        internal static string CustomerEvaluation {
            get {
                return ResourceManager.GetString("CustomerEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device recipe wrong or missing.
        /// </summary>
        internal static string DeviceRecipeWrong {
            get {
                return ResourceManager.GetString("DeviceRecipeWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices parameters.
        /// </summary>
        internal static string DevicesParameters {
            get {
                return ResourceManager.GetString("DevicesParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitizer.
        /// </summary>
        internal static string Digitizer {
            get {
                return ResourceManager.GetString("Digitizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download images.
        /// </summary>
        internal static string DownloadImages {
            get {
                return ResourceManager.GetString("DownloadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading images.
        /// </summary>
        internal static string DownloadingImages {
            get {
                return ResourceManager.GetString("DownloadingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading images cameras .....
        /// </summary>
        internal static string DownLoadParam {
            get {
                return ResourceManager.GetString("DownLoadParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump.
        /// </summary>
        internal static string Dump {
            get {
                return ResourceManager.GetString("Dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera recipe parameters {0} cannot be read.
        /// </summary>
        internal static string ElaborationGetError {
            get {
                return ResourceManager.GetString("ElaborationGetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Knapp.
        /// </summary>
        internal static string EnableKnapp {
            get {
                return ResourceManager.GetString("EnableKnapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while generating report.
        /// </summary>
        internal static string ErrorReport {
            get {
                return ResourceManager.GetString("ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending parameters.
        /// </summary>
        internal static string ErrorSendingParameters {
            get {
                return ResourceManager.GetString("ErrorSendingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting knapp.
        /// </summary>
        internal static string ErrorStartingKnapp {
            get {
                return ResourceManager.GetString("ErrorStartingKnapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error stopping knapp.
        /// </summary>
        internal static string ErrorStoppingKnapp {
            get {
                return ResourceManager.GetString("ErrorStoppingKnapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading parameters.
        /// </summary>
        internal static string ErrorUploadingParameters {
            get {
                return ResourceManager.GetString("ErrorUploadingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation scale.
        /// </summary>
        internal static string EvaluationScale {
            get {
                return ResourceManager.GetString("EvaluationScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export camera params.
        /// </summary>
        internal static string ExportCameraParams {
            get {
                return ResourceManager.GetString("ExportCameraParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export vial axis.
        /// </summary>
        internal static string ExportVialAxis {
            get {
                return ResourceManager.GetString("ExportVialAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error! Check configuration and restart.
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get Features from camera {0}.
        /// </summary>
        internal static string FeaturesGetError {
            get {
                return ResourceManager.GetString("FeaturesGetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        internal static string Frames {
            get {
                return ResourceManager.GetString("Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FW ver..
        /// </summary>
        internal static string FWver {
            get {
                return ResourceManager.GetString("FWver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get parameters failed.
        /// </summary>
        internal static string GetParametersFailed {
            get {
                return ResourceManager.GetString("GetParametersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gretel PCs.
        /// </summary>
        internal static string GretelPCs {
            get {
                return ResourceManager.GetString("GretelPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard reset.
        /// </summary>
        internal static string HardReset {
            get {
                return ResourceManager.GetString("HardReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMI Enable.
        /// </summary>
        internal static string HMIEnable {
            get {
                return ResourceManager.GetString("HMIEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Id.
        /// </summary>
        internal static string IdTool {
            get {
                return ResourceManager.GetString("IdTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image saved.
        /// </summary>
        internal static string ImageSaved {
            get {
                return ResourceManager.GetString("ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images downloaded successfully.
        /// </summary>
        internal static string ImagesDownloaded {
            get {
                return ResourceManager.GetString("ImagesDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images downloads.
        /// </summary>
        internal static string ImagesDownloads {
            get {
                return ResourceManager.GetString("ImagesDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images dump settings.
        /// </summary>
        internal static string ImagesDumpSettings {
            get {
                return ResourceManager.GetString("ImagesDumpSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images download failed.
        /// </summary>
        internal static string ImagesNotDownloaded {
            get {
                return ResourceManager.GetString("ImagesNotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images upload failed.
        /// </summary>
        internal static string ImagesNotUploaded {
            get {
                return ResourceManager.GetString("ImagesNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images upload.
        /// </summary>
        internal static string ImagesUpload {
            get {
                return ResourceManager.GetString("ImagesUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images uploads.
        /// </summary>
        internal static string ImagesUploads {
            get {
                return ResourceManager.GetString("ImagesUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment.
        /// </summary>
        internal static string Increment {
            get {
                return ResourceManager.GetString("Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection.
        /// </summary>
        internal static string Inspection {
            get {
                return ResourceManager.GetString("Inspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection settings.
        /// </summary>
        internal static string InspectionSettings {
            get {
                return ResourceManager.GetString("InspectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid light controller.
        /// </summary>
        internal static string InvalidLightCtrl {
            get {
                return ResourceManager.GetString("InvalidLightCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knapp.
        /// </summary>
        internal static string Knapp {
            get {
                return ResourceManager.GetString("Knapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knapp idle.
        /// </summary>
        internal static string KnappIdle {
            get {
                return ResourceManager.GetString("KnappIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knapp running.
        /// </summary>
        internal static string KnappRunning {
            get {
                return ResourceManager.GetString("KnappRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knapp settings error.
        /// </summary>
        internal static string KnappSettingsError {
            get {
                return ResourceManager.GetString("KnappSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live mode ROI.
        /// </summary>
        internal static string LiveMode {
            get {
                return ResourceManager.GetString("LiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live mode fullframe.
        /// </summary>
        internal static string LiveModeFF {
            get {
                return ResourceManager.GetString("LiveModeFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load recipe and apply.
        /// </summary>
        internal static string LoadRecipeAndApply {
            get {
                return ResourceManager.GetString("LoadRecipeAndApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load recipe without apply.
        /// </summary>
        internal static string LoadRecipeWithoutApply {
            get {
                return ResourceManager.GetString("LoadRecipeWithoutApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine evaluation.
        /// </summary>
        internal static string MachineEvaluation {
            get {
                return ResourceManager.GetString("MachineEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine parameter.
        /// </summary>
        internal static string MachineParameter {
            get {
                return ResourceManager.GetString("MachineParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max value.
        /// </summary>
        internal static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min value.
        /// </summary>
        internal static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module name.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network nodes.
        /// </summary>
        internal static string NetworkNodes {
            get {
                return ResourceManager.GetString("NetworkNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active recipe.
        /// </summary>
        internal static string NoActiveRecipe {
            get {
                return ResourceManager.GetString("NoActiveRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No camera available!.
        /// </summary>
        internal static string NoCameraAvailable {
            get {
                return ResourceManager.GetString("NoCameraAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node id.
        /// </summary>
        internal static string NodeId {
            get {
                return ResourceManager.GetString("NodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter editing not admitted in this moment!.
        /// </summary>
        internal static string NoEditingAvailable {
            get {
                return ResourceManager.GetString("NoEditingAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit from parameter editing not admitted in this moment!.
        /// </summary>
        internal static string NoReadyToRunAvailable {
            get {
                return ResourceManager.GetString("NoReadyToRunAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recipe available!.
        /// </summary>
        internal static string NoRecipeAvailable {
            get {
                return ResourceManager.GetString("NoRecipeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalization.
        /// </summary>
        internal static string Normalization {
            get {
                return ResourceManager.GetString("Normalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline analysis.
        /// </summary>
        internal static string OfflineAnalysis {
            get {
                return ResourceManager.GetString("OfflineAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel info.
        /// </summary>
        internal static string PixelInfo {
            get {
                return ResourceManager.GetString("PixelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait windows service.
        /// </summary>
        internal static string PleaseWaitWindowsService {
            get {
                return ResourceManager.GetString("PleaseWaitWindowsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Knapp.
        /// </summary>
        internal static string PrintKnapp {
            get {
                return ResourceManager.GetString("PrintKnapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.U.M..
        /// </summary>
        internal static string PUM {
            get {
                return ResourceManager.GetString("PUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading device info.
        /// </summary>
        internal static string ReadingDeviceInfo {
            get {
                return ResourceManager.GetString("ReadingDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get recipe advanced parameters from camera {0}.
        /// </summary>
        internal static string RecipeAdvancedGetError {
            get {
                return ResourceManager.GetString("RecipeAdvancedGetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Enable.
        /// </summary>
        internal static string RecipeEnable {
            get {
                return ResourceManager.GetString("RecipeEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get recipe machine parameters from camera {0}.
        /// </summary>
        internal static string RecipeMachineGetError {
            get {
                return ResourceManager.GetString("RecipeMachineGetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe parameters.
        /// </summary>
        internal static string RecipeParameter {
            get {
                return ResourceManager.GetString("RecipeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get recipe simple parameters from camera {0}.
        /// </summary>
        internal static string RecipeSimpleGetError {
            get {
                return ResourceManager.GetString("RecipeSimpleGetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received recipe with errors. The recipe has been ignored..
        /// </summary>
        internal static string RecivedRecipeWithErrors {
            get {
                return ResourceManager.GetString("RecivedRecipeWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record images error.
        /// </summary>
        internal static string RecordImagesError {
            get {
                return ResourceManager.GetString("RecordImagesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejects.
        /// </summary>
        internal static string Rejects {
            get {
                return ResourceManager.GetString("Rejects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejects buffer.
        /// </summary>
        internal static string RejectsBuffer {
            get {
                return ResourceManager.GetString("RejectsBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all.
        /// </summary>
        internal static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset buffer images.
        /// </summary>
        internal static string ResetBufferImages {
            get {
                return ResourceManager.GetString("ResetBufferImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset camera failed.
        /// </summary>
        internal static string ResetError {
            get {
                return ResourceManager.GetString("ResetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset trigger encoder.
        /// </summary>
        internal static string ResetTriggerEncoder {
            get {
                return ResourceManager.GetString("ResetTriggerEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore vial axis failed.
        /// </summary>
        internal static string RestoreVialAxisFailed {
            get {
                return ResourceManager.GetString("RestoreVialAxisFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROI definition.
        /// </summary>
        internal static string ROIDefinition {
            get {
                return ResourceManager.GetString("ROIDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round turn.
        /// </summary>
        internal static string RoundNum {
            get {
                return ResourceManager.GetString("RoundNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds num.
        /// </summary>
        internal static string RoundsNum {
            get {
                return ResourceManager.GetString("RoundsNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run failed.
        /// </summary>
        internal static string RunFailed {
            get {
                return ResourceManager.GetString("RunFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running mode.
        /// </summary>
        internal static string RunningMode {
            get {
                return ResourceManager.GetString("RunningMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample size.
        /// </summary>
        internal static string SampleSize {
            get {
                return ResourceManager.GetString("SampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save buffered images.
        /// </summary>
        internal static string SaveBufferedImages {
            get {
                return ResourceManager.GetString("SaveBufferedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current recipe.
        /// </summary>
        internal static string SaveCurrentRecipe {
            get {
                return ResourceManager.GetString("SaveCurrentRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Knapp.
        /// </summary>
        internal static string SaveKnapp {
            get {
                return ResourceManager.GetString("SaveKnapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save rejected containers images.
        /// </summary>
        internal static string SaveRejectedContainersImages {
            get {
                return ResourceManager.GetString("SaveRejectedContainersImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save survey.
        /// </summary>
        internal static string SaveSurvey {
            get {
                return ResourceManager.GetString("SaveSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving buffered images.
        /// </summary>
        internal static string SavingBufferedImages {
            get {
                return ResourceManager.GetString("SavingBufferedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving recipe ....
        /// </summary>
        internal static string SavingCurrentRecipe {
            get {
                return ResourceManager.GetString("SavingCurrentRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving current recipe failed.
        /// </summary>
        internal static string SavingCurrentRecipeFailed {
            get {
                return ResourceManager.GetString("SavingCurrentRecipeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder for saving images.
        /// </summary>
        internal static string SelectFolderForSavingImages {
            get {
                return ResourceManager.GetString("SelectFolderForSavingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder from which to upload.
        /// </summary>
        internal static string SelectFolderFromWhichToUpload {
            get {
                return ResourceManager.GetString("SelectFolderFromWhichToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending recipe to.
        /// </summary>
        internal static string SendingRecipeTo {
            get {
                return ResourceManager.GetString("SendingRecipeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending parameters to the cameras ....
        /// </summary>
        internal static string SendParam {
            get {
                return ResourceManager.GetString("SendParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing live cam!.
        /// </summary>
        internal static string ShowingLiveCam {
            get {
                return ResourceManager.GetString("ShowingLiveCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft reset.
        /// </summary>
        internal static string SoftReset {
            get {
                return ResourceManager.GetString("SoftReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle.
        /// </summary>
        internal static string Spindle {
            get {
                return ResourceManager.GetString("Spindle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send &apos;Busy&apos; state.
        /// </summary>
        internal static string SpvBusyError {
            get {
                return ResourceManager.GetString("SpvBusyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send &apos;Error&apos; state.
        /// </summary>
        internal static string SpvErrorError {
            get {
                return ResourceManager.GetString("SpvErrorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send &apos;ReadyToRun&apos; state.
        /// </summary>
        internal static string SpvReadyToRunError {
            get {
                return ResourceManager.GetString("SpvReadyToRunError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start live.
        /// </summary>
        internal static string StartLive {
            get {
                return ResourceManager.GetString("StartLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start offline analysis.
        /// </summary>
        internal static string StartOfflineAnalysis {
            get {
                return ResourceManager.GetString("StartOfflineAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start offset.
        /// </summary>
        internal static string StartOffset {
            get {
                return ResourceManager.GetString("StartOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start run.
        /// </summary>
        internal static string StartRun {
            get {
                return ResourceManager.GetString("StartRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station evaluation.
        /// </summary>
        internal static string StationEvaluation {
            get {
                return ResourceManager.GetString("StationEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Id.
        /// </summary>
        internal static string StationId {
            get {
                return ResourceManager.GetString("StationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station rejects.
        /// </summary>
        internal static string StationRejects {
            get {
                return ResourceManager.GetString("StationRejects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station spindle initial position.
        /// </summary>
        internal static string StationSpindleInitialPosition {
            get {
                return ResourceManager.GetString("StationSpindleInitialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station spindle offset.
        /// </summary>
        internal static string StationSpindleOffset {
            get {
                return ResourceManager.GetString("StationSpindleOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop live.
        /// </summary>
        internal static string StopLive {
            get {
                return ResourceManager.GetString("StopLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop off. analysis.
        /// </summary>
        internal static string StopOffAnalysis {
            get {
                return ResourceManager.GetString("StopOffAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop offline analysis.
        /// </summary>
        internal static string StopOfflineAnalysis {
            get {
                return ResourceManager.GetString("StopOfflineAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop on condition.
        /// </summary>
        internal static string StopOnCondition {
            get {
                return ResourceManager.GetString("StopOnCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strobe.
        /// </summary>
        internal static string Strobe {
            get {
                return ResourceManager.GetString("Strobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strobo.
        /// </summary>
        internal static string Strobo {
            get {
                return ResourceManager.GetString("Strobo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strobo configuration file invalid. Check strobo number and paths..
        /// </summary>
        internal static string StroboConfFileInvalid {
            get {
                return ResourceManager.GetString("StroboConfFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strobo configuration parameter.
        /// </summary>
        internal static string StroboParameter {
            get {
                return ResourceManager.GetString("StroboParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW Version.
        /// </summary>
        internal static string SwVersion {
            get {
                return ResourceManager.GetString("SwVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Reject.
        /// </summary>
        internal static string TechnicalReject {
            get {
                return ResourceManager.GetString("TechnicalReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        internal static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool description.
        /// </summary>
        internal static string ToolDescription {
            get {
                return ResourceManager.GetString("ToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Id.
        /// </summary>
        internal static string ToolId {
            get {
                return ResourceManager.GetString("ToolId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To save.
        /// </summary>
        internal static string ToSave {
            get {
                return ResourceManager.GetString("ToSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read machine configuration!.
        /// </summary>
        internal static string UnableReadMacConf {
            get {
                return ResourceManager.GetString("UnableReadMacConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading images.
        /// </summary>
        internal static string UploadingImages {
            get {
                return ResourceManager.GetString("UploadingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User level: {0}.
        /// </summary>
        internal static string UserLevelMsg {
            get {
                return ResourceManager.GetString("UserLevelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User settings.
        /// </summary>
        internal static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        internal static string Utilities {
            get {
                return ResourceManager.GetString("Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vial axis.
        /// </summary>
        internal static string VialAxis {
            get {
                return ResourceManager.GetString("VialAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vial axis exported successfully.
        /// </summary>
        internal static string VialAxisExportedOk {
            get {
                return ResourceManager.GetString("VialAxisExportedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vial axis imported successfully.
        /// </summary>
        internal static string VialAxisImportedOk {
            get {
                return ResourceManager.GetString("VialAxisImportedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vial Id.
        /// </summary>
        internal static string VialId {
            get {
                return ResourceManager.GetString("VialId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vial offset.
        /// </summary>
        internal static string VialOffset {
            get {
                return ResourceManager.GetString("VialOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vials to ignore num.
        /// </summary>
        internal static string VialsToIgnoreNum {
            get {
                return ResourceManager.GetString("VialsToIgnoreNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string ViewParameters {
            get {
                return ResourceManager.GetString("ViewParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision spv cannot be executed.
        /// </summary>
        internal static string VisionSpvCannotBeExecuted {
            get {
                return ResourceManager.GetString("VisionSpvCannotBeExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision spv is waiting for system startup.
        /// </summary>
        internal static string VisionSpvIsWaitingForSystemStartup {
            get {
                return ResourceManager.GetString("VisionSpvIsWaitingForSystemStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VNC connection error.
        /// </summary>
        internal static string VNCError {
            get {
                return ResourceManager.GetString("VNCError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0} connection... {1}.
        /// </summary>
        internal static string WaitingNodeConnection {
            get {
                return ResourceManager.GetString("WaitingNodeConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working mode.
        /// </summary>
        internal static string WorkingMode {
            get {
                return ResourceManager.GetString("WorkingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
